### PR TITLE
Deduplicate Mailchimp newsletter subscriptions

### LINKED ISSUE #279: Signing up a changemaker who's already subscribed to newsletters fails

### PR DESCRIPTION
**Pull request by kevincianfarini**
It's possible that a Changemaker could already be subscribed for our
newsletter. If this was the case, Mailchimp would fail to sign a new
changemaker up in our audience because of a data conflict.

This commit uniquely identifies a changemaker by taking the MD5 hash of
their email address.

Closes #279

### CODE REVIEW

File: backend/src/main/kotlin/org/climatechangemakers/act/feature/email/service/MailchimpService.kt [hunk 1]
```diff
@@ -1,15 +1,16 @@
...
-import retrofit2.http.Body
-import retrofit2.http.POST
+import retrofit2.http.PUT
 import retrofit2.http.Path
+import retrofit2.http.Body
 
 interface MailchimpService {
 
-  @POST("lists/{audience_id}/members/")
+  @PUT("lists/{audience_id}/members/{email_md5_hash_string}")
```
Comment (kevincianfarini) [inline backend/src/main/kotlin/org/climatechangemakers/act/feature/email/service/MailchimpService.kt:10]: This _updates_ a given row in the mailchimp audience if it exists. If it doesn't, then it adds it.

**Review by jacknugent — APPROVED** [review]
